Develop
Wirt150/java-explore-with-me pull request #2
Opened 2023-01-04 23:14 UTC by Wirt150

Выполнение дипломного проекта.

2023-01-05 21:16 UTC, db-exp requested changes

2023-01-06 19:16 UTC, Wirt150 commented on ewm-service/src/main/java/ru/practicum/ewm_service/config/exception/GlobalExceptionController.java
> +                .status(HttpStatus.NOT_FOUND)
Торопился и переживал из-за неверно работающего парсинга времени. Поправил!

2023-01-06 19:26 UTC, Wirt150 commented on ewm-service/src/main/java/ru/practicum/ewm_service/config/exception/GlobalExceptionController.java
> +                .status(HttpStatus.NOT_FOUND)
Привет!

2023-01-06 19:42 UTC, db-exp approved these changes

2023-01-06 20:09 UTC, merged